# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Castlegate Holdings LLC
email: CastlegateHoldingsLLC@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Tiny House Village to call our own. A place where we can gather,
  relax, and recreate. This is a living project and dream for many of us.
  Here we can document our progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
